### ISSUE TITLE
Training on a single GPU?

### ISSUE THREAD

**Issue by NeuralBricolage** [pfnet-research/chainer-stylegan#1]
have you tried or do you think it's possible to train on a single 1080 GTX TI? Provided i don't need hi-res of 1024X1024?
thank you!

**Comment by Aixile** [comment]
I added a reference training configuration for 1 GPU setting.
Please use
```
cd src/stylegan
bash run_ffhq.sh 1
```
(Have not tested)

**Comment by NeuralBricolage** [comment]
great, thank you so much!
